const Router = require('express')
const router = new Router()
const categoryRouter = require('./categoryRouter')
const faqRouter = require('./faqRouter')
const ingredientRouter = require('./ingredientRouter')
const mealPlanRouter = require('./mealPlanRouter')
const orderRouter = require('./orderRouter')
const privilegeRouter = require('./privilegeRouter')
const productRouter = require('./productRouter')
const roleRouter = require('./roleRouter')
const tariffRouter = require('./tariffRouter')
const typeRouter = require('./typeRouter')
const userRouter = require('./userRouter')
const favoriteProductRouter = require('./favoriteProductRouter')
const favoriteIngredientRouter = require('./favoriteIngredientRouter')
const unlovedIngredientRouter = require('./unlovedIngredientRouter')
const typeOrderRouter = require('./typeOrderRouter')
const reviewRouter = require('./reviewRouter')

router.use('/category', categoryRouter)
router.use('/typeorder', typeOrderRouter)
router.use('/faq', faqRouter)
router.use('/type', typeRouter)
router.use('/role', roleRouter)
router.use('/user', userRouter)
router.use('/product', productRouter)
router.use('/ingredient', ingredientRouter)
router.use('/mealplan', mealPlanRouter)
router.use('/order', orderRouter)
router.use('/review', reviewRouter)
router.use('/privilege', privilegeRouter)
router.use('/tariff', tariffRouter)
router.use('/favoriteproduct', favoriteProductRouter)
router.use('/favoriteingredient', favoriteIngredientRouter)
router.use('/unlovedingredient', unlovedIngredientRouter)


module.exports = router